### ISSUE TITLE
Can you provide a requirement.txt file？

### ISSUE THREAD

**Issue by zhuliwen** [hemilpanchiwala/Hindsight-Experience-Replay#2]
Can you provide a requirement.txt file？Thanks.

**Comment by hemilpanchiwala** [comment]
@zhuliwen, I have added the requirements.txt file. Link [here](https://github.com/hemilpanchiwala/Hindsight-Experience-Replay/blob/main/requirements.txt). If there are some issues after using this, feel free to write here again.

**Comment by zhuliwen** [comment]
Thank you~
