### ISSUE TITLE
Change reward for HER+DQN

### ISSUE THREAD

**Issue by fnuabhimanyu** [hemilpanchiwala/Hindsight-Experience-Replay#3]
https://github.com/hemilpanchiwala/Hindsight-Experience-Replay/blob/8287aa37ff8c8beebc9f29c991ced57b166cbdae/dqn_with_her/HERmain.py#L60

Shouldn't the transition[2] which refers to the reward collected during the step should be equal to 1(assuming reward=1 for completing the task) as the agent is able to reach the new_goal set by the HER. Or am I missing something?

**Comment by hemilpanchiwala** [comment]
@Abhimanyu8713, yes it seems to be an issue in the code. Will update it soon.
